// <auto-generated />
namespace PollBooth.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddSecurity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSecurity));
        
        string IMigrationMetadata.Id
        {
            get { return "201405031838572_AddSecurity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
